# Generated by Django 5.2.6 on 2025-09-23 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='non title', verbose_name='title'),
            preserve_default=False,
        ),
    ]
