# Generated by Django 5.2.6 on 2025-10-02 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='body',
        ),
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
