# Generated by Django 5.2.6 on 2025-10-03 01:04

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post2', '0002_remove_blog_body_alter_blog_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('description', tinymce.models.HTMLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='description',
        ),
    ]
