# Generated by Django 5.2.6 on 2025-10-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post2', '0005_alter_blog2_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=10)),
            ],
        ),
    ]
