# Generated by Django 5.2.6 on 2025-10-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post2', '0006_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog2',
            name='hashTag',
            field=models.ManyToManyField(blank=True, to='post2.hashtag'),
        ),
    ]
