# Generated by Django 5.2.6 on 2025-11-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_created=True, verbose_name='addedDate')),
                ('content', models.CharField(max_length=100, verbose_name='content')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_created=True, verbose_name='addedDate')),
                ('content', models.CharField(max_length=100, verbose_name='content')),
            ],
        ),
    ]
