# Generated by Django 5.2.6 on 2025-11-11 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.CharField(default=12, max_length=100, verbose_name='content'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post3.content', verbose_name='답변들'),
        ),
        migrations.AlterField(
            model_name='content',
            name='content',
            field=models.CharField(max_length=100, verbose_name='문의들'),
        ),
    ]
