# Generated by Django 5.2.6 on 2025-11-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post3', '0004_comment_user_alter_content_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='addedDate'),
        ),
        migrations.AlterField(
            model_name='content',
            name='content',
            field=models.CharField(max_length=100, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='content',
            name='pub_date',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='addedDate'),
        ),
    ]
